### ISSUE TITLE
help me 

### ISSUE THREAD

**Issue by czadikem** [G10DRAS/RoboCop#33]
First where is the android app.  Second can you incorporate aiml2.0.

Thanks

**Comment by czadikem** [comment]
Also can you make a video so I can see how this works.

**Comment by czadikem** [comment]
[GitHub](http://github.com)

**Comment by czadikem** [comment]
I just tried to install got errors " Could not find a version that satisfies the requirement futures==3.2.0 (from -r python_requirement.txt (line 37)) (from versions: 0.2.python3, 0.1, 0.2, 1.0, 2.0, 2.1, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5, 3.1.0, 3.1.1)
No matching distribution found for futures==3.2.0 (from -r python_requirement.txt (line 37))
" using pip3

**Comment by G10DRAS** [comment]
1. Android App I havent released yet, It is developed using MIT AppInventor.
2. It is using https://github.com/G10DRAS/WavSoundRecorderExtension plugin.
3. aiml2.0 is not a big task, I will probably do it in next week.
4. For futures==3.2.0 see this https://pypi.org/project/futures , it is available for python 2.7

https://pypi.org/project/futures/

**Comment by czadikem** [comment]
thanks

**Comment by czadikem** [comment]
So is this suppose
 to run on python 2 or 3
thanks

**Comment by czadikem** [comment]
also can you make a install guide

**Comment by G10DRAS** [comment]
1. Project runs 100% on Python 2.7, but 40% on Python 3.x.

2. Multiple install guides as project consists of many sub-projects.

**Comment by czadikem** [comment]
I am trying to use this as my ai for my robot Inmoov instead of the python J.A.R.V.I.S. because there seem to be more that this can do.  Also I would be willing to help you though I do not know python.
