### ISSUE TITLE
Aiml 2.0

### ISSUE THREAD

**Issue by montanaman2017** [G10DRAS/RoboCop#34]
There is a lot of options with AIML 1.0 but nothing like what you have.  I'd love to understand your roadmap more and also if you are going to be updating this for Aiml 2.0?  If so, this could be really awesome with a robot (based of Inmoov) that I am working on.   Let me know.  Thanks

**Comment by G10DRAS** [comment]
I am using AIML 1.0 on experimental basis, its not fully integrated with my project.

**Comment by montanaman2017** [comment]
yah we gave up and moved on.  It appears this project has not progressed much :( .. maybe check back again in a few months
