### ISSUE TITLE
any code for it?

### ISSUE THREAD

**Issue by Arvrairobo** [G10DRAS/RoboCop#35]
do we have any code for it? why there is no code?

**Comment by G10DRAS** [comment]
Not yet released

**Comment by Arvrairobo** [comment]
when do you think you will release it? i have seen you are working on it since many years, lots of hard work :) but you are doing great! what is your expectation with robocop?

**Comment by G10DRAS** [comment]
:) Everything will be offline, ie STT, TTS, NLP.
TTS will be using your own voice.

**Comment by Arvrairobo** [comment]
COOL :) what will be a cost of it when you launch the robocop?

**Comment by Arvrairobo** [comment]
and also tentative date of releasing a code?

**Comment by G10DRAS** [comment]
It needs lots of documentation, and I don't have time right now.
If I release it without doc there will be 1000 questions for sure.

**Comment by Arvrairobo** [comment]
that is correct, i can help you to build a document if you want, let me know!

**Comment by Arvrairobo** [comment]
so what do you think? if i can help you to build a document?

**Comment by G10DRAS** [comment]
Not an easy task.

**Comment by Arvrairobo** [comment]
True, but one day or some day, you have to start it from somewhere? then why not now?
